###########################################################################
# Makefile: bash ara automatizar instrucciones de compilación
# Se requiere automatizar la compilación
# Nombre: Carolina Ujueta
# Fecha: 12/08/2025
###########################################################################

GCC = gcc
BIBLIOTECAS =
MODULOS = generalMM.c

PROGRAMAS = generalMM

all: $(PROGRAMAS)

generalMM:
	$(GCC) $(MODULOS) -o $@
