# ============================================================================
# Makefile - Laboratorios de Sistemas Operativos
# Autor: Carolina Ujueta
# Universidad Javeriana
# Profesor: John Corredor
# ============================================================================

CC = gcc

all: lab1 lab2 lab3 lab4 lab5 lab6 lab7 lab8 lab9

lab1: lab1.c
	$(CC) lab1.c -o lab1 -lpthread

lab2: lab2.c
	$(CC) lab2.c -o lab2 -lpthread

lab3: lab3.c
	$(CC) lab3.c -o lab3 -lpthread

lab4: lab4.c
	$(CC) lab4.c -o lab4 -lpthread

lab5: lab5.c
	$(CC) lab5.c -o lab5 -lpthread

lab6: lab6.c
	$(CC) lab6.c -o lab6 -lpthread

lab7: lab7.c
	$(CC) lab7.c -o lab7 -lpthread

lab8: lab8.c
	$(CC) lab8.c -o lab8 -lpthread

lab9: lab9.c
	$(CC) lab9.c -o lab9 -lpthread

clean:
	rm -f lab1 lab2 lab3 lab4 lab5 lab6 lab7 lab8 lab9
