CC = gcc

# Ejecutables
PROGS = reto01 reto02 reto03 reto04 reto05

all: $(PROGS)

reto01: reto01.c
	$(CC) -o $@ $^

reto02: reto02.c
	$(CC) -o $@ $^

reto03: reto03.c
	$(CC) -o $@ $^

reto04: reto04.c
	$(CC) -o $@ $^

reto05: reto05.c
	$(CC) -o $@ $^

clean:
	rm -f $(PROGS)
