# ********************************************
# Makefile - Laboratorios de Sistemas Operativos
# Autor: Carolina Ujueta
# Fecha: 07/10/2025
# Tema: Uso de la función fork() y creación de procesos
# ********************************************

CC = gcc

all: lab01 lab02 lab03

lab01: lab01.c
	$(CC) lab01.c -o lab01

lab02: lab02.c
	$(CC) lab02.c -o lab02

lab03: lab03.c
	$(CC) lab03.c -o lab03

clean:
	rm -f lab01 lab02 lab03
